"""Shared constants used across backend modules."""

from __future__ import annotations

CLASS_LABELS = [
    "Adialer.C",
    "Agent.FYI",
    "Allaple.A",
    "Allaple.L",
    "Alueron.gen!J",
    "Autorun.K",
    "C2LOP.gen!g",
    "C2LOP.P",
    "Dialplatform.B",
    "Dontovo.A",
    "Fakerean",
    "Instantaccess",
    "Lolyda.AA1",
    "Lolyda.AA2",
    "Lolyda.AA3",
    "Lolyda.AT",
    "Malex.gen!J",
    "Obfuscator.AD",
    "Rbot!gen",
    "Skintrim.N",
    "Swizzor.gen!E",
    "Swizzor.gen!I",
    "VB.AT",
    "Wintrim.BX",
    "Yuner.A",
    "Benign",
]


SUSPICIOUS_API_VOCAB = [
    "CreateRemoteThread", "VirtualAlloc", "VirtualAllocEx", "WriteProcessMemory",
    "ReadProcessMemory", "OpenProcess", "NtOpenProcess", "WinExec",
    "ShellExecuteA", "ShellExecuteW", "CreateProcessA", "CreateProcessW",
    "CreateToolhelp32Snapshot", "Process32First", "Process32Next", "LoadLibraryA",
    "LoadLibraryW", "GetProcAddress", "InternetOpenA", "InternetOpenW",
    "InternetConnectA", "InternetConnectW", "HttpOpenRequestA", "HttpSendRequestA",
    "URLDownloadToFileA", "URLDownloadToFileW", "WSAStartup", "socket", "connect",
    "send", "recv", "bind", "listen", "accept", "closesocket",
    "GetAdaptersInfo", "GetAdaptersAddresses", "DnsQuery_A", "DnsQuery_W",
    "CryptEncrypt", "CryptDecrypt", "CryptAcquireContextA", "CryptAcquireContextW",
    "CryptGenRandom", "BCryptEncrypt", "BCryptDecrypt", "RegOpenKeyExA",
    "RegOpenKeyExW", "RegSetValueExA", "RegSetValueExW", "RegCreateKeyExA",
    "RegCreateKeyExW", "SetWindowsHookExA", "SetWindowsHookExW", "GetAsyncKeyState",
    "GetKeyState", "MapViewOfFile", "CreateFileMappingA", "CreateFileMappingW",
    "CreateFileA", "CreateFileW", "WriteFile", "ReadFile", "DeleteFileA",
    "DeleteFileW", "MoveFileExA", "MoveFileExW", "CopyFileA", "CopyFileW",
    "SetFileAttributesA", "SetFileAttributesW", "GetTempPathA", "GetTempPathW",
    "GetTempFileNameA", "GetTempFileNameW", "FindFirstFileA", "FindFirstFileW",
    "FindNextFileA", "FindNextFileW", "FindResourceA", "FindResourceW",
    "LoadResource", "SizeofResource", "BeginUpdateResourceA", "UpdateResourceA",
    "EndUpdateResourceA", "OpenSCManagerA", "OpenServiceA", "CreateServiceA",
    "StartServiceA", "ControlService", "DeleteService", "OpenSCManagerW",
    "CreateServiceW", "StartServiceW", "CoCreateInstance", "IWbemServices",
    "NetShareEnum", "NetUserEnum", "LookupPrivilegeValueA", "AdjustTokenPrivileges",
    "OpenProcessToken", "DuplicateTokenEx", "CreateMutexA", "CreateMutexW",
    "OpenMutexA", "OpenMutexW", "IsDebuggerPresent", "CheckRemoteDebuggerPresent",
    "OutputDebugStringA", "OutputDebugStringW", "TerminateProcess", "ExitProcess",
    "Sleep", "NtDelayExecution", "SetUnhandledExceptionFilter", "UnhandledExceptionFilter",
    "CreateNamedPipeA", "CreateNamedPipeW", "ConnectNamedPipe", "PeekNamedPipe",
    "GetModuleFileNameA", "GetModuleFileNameW", "GetStartupInfoA", "GetStartupInfoW",
    "GetTickCount", "QueryPerformanceCounter", "NtQueryInformationProcess",
    "NtQuerySystemInformation", "CreateDirectoryA", "CreateDirectoryW", "RemoveDirectoryA",
    "RemoveDirectoryW", "SHGetFolderPathA", "SHGetFolderPathW", "SHChangeNotify",
    "SetCurrentDirectoryA", "SetCurrentDirectoryW", "GetDriveTypeA", "GetDriveTypeW",
    "GetVolumeInformationA", "GetVolumeInformationW", "DeviceIoControl", "EnumProcesses",
    "EnumProcessModules", "GetModuleBaseNameA", "GetModuleBaseNameW", "OpenThread",
    "SuspendThread", "ResumeThread", "QueueUserAPC", "CreateRemoteThreadEx",
    "NtWriteVirtualMemory", "NtReadVirtualMemory", "NtResumeThread", "SetThreadContext",
    "GetThreadContext", "Wow64GetThreadContext", "Wow64SetThreadContext",
    "EnumWindows", "GetWindowThreadProcessId", "FindWindowA", "FindWindowW",
    "SetForegroundWindow", "ShowWindow", "MessageBoxA", "MessageBoxW",
    "GetSystemMetrics", "GetComputerNameA", "GetComputerNameW", "GetUserNameA",
    "GetUserNameW", "GetVersionExA", "GetVersionExW", "GetSystemDirectoryA",
    "GetSystemDirectoryW", "GetWindowsDirectoryA", "GetWindowsDirectoryW", "LdrLoadDll",
    "RtlDecompressBuffer", "RtlCompressBuffer", "MiniDumpWriteDump", "CreatePipe",
    "SetStdHandle", "GetStdHandle", "PowerShell", "cmd.exe", "rundll32.exe",
    "wscript.exe", "cscript.exe", "mshta.exe", "schtasks.exe", "powershell.exe",
    "vssadmin.exe", "wbadmin.exe", "bcdedit.exe", "taskkill.exe", "netsh.exe",
    "sc.exe", "wevtutil.exe", "whoami.exe", "ipconfig.exe", "attrib.exe",
    "net.exe", "ping.exe", "bitsadmin.exe", "certutil.exe", "wmic.exe",
]


TOP_BIGRAM_INDICES = [
    ((i * 257) + (i % 13) * 11) % 65536 for i in range(256)
]
