import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import client, { safeRequest } from "../api/client";
import SectionCard from "../components/layout/SectionCard";
import StatCard from "../components/evolution/StatCard";

const chartPalette = ["#22e1c3", "#47c0ff", "#ffb84d", "#ff6b6b", "#57e389", "#8ddcff"];

export default function AnalyticsPage() {
  const [data, setData] = useState(null);

  useEffect(() => {
    const load = async () => {
      const { data: payload } = await safeRequest(() => client.get("/api/analytics"));
      if (payload) setData(payload);
    };
    load();
    const timer = window.setInterval(load, 20000);
    return () => window.clearInterval(timer);
  }, []);

  const overview = data?.overview ?? {};

  return (
    <main className="page-shell grid-shell space-y-6">
      <section className="glass-card p-6">
        <p className="text-sm uppercase tracking-[0.35em] text-aegis-primary">Threat Analytics</p>
        <h1 className="mt-3 text-4xl font-bold">System-wide detection trends, YARA activity, and confidence distribution.</h1>
      </section>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total Scans" value={overview.scan_count ?? 0} accent="text-aegis-primary" />
        <StatCard label="Total Alerts" value={overview.alert_count ?? 0} accent="text-aegis-danger" />
        <StatCard label="Incidents" value={overview.incident_count ?? 0} accent="text-aegis-warning" />
        <StatCard label="Avg Scan Time" value={`${overview.avg_scan_time_ms ?? 0}ms`} accent="text-aegis-info" />
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="Detection Timeline" subtitle="Recent scan throughput buckets that power the command-center trendline.">
          <div className="h-72">
            <ResponsiveContainer>
              <BarChart data={data?.timeline ?? []}>
                <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                <XAxis dataKey="bucket" hide />
                <YAxis tick={{ fill: "#d6e2ef", fontSize: 12 }} />
                <Tooltip />
                <Bar dataKey="count" fill="#22e1c3" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </SectionCard>

        <SectionCard title="Family Distribution" subtitle="Top predicted families across manual scans and watcher-driven scans.">
          <div className="h-72">
            <ResponsiveContainer>
              <PieChart>
                <Pie data={data?.family_distribution ?? []} dataKey="count" nameKey="family" innerRadius={60} outerRadius={95}>
                  {(data?.family_distribution ?? []).map((entry, index) => (
                    <CellShim key={entry.family} fill={chartPalette[index % chartPalette.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </SectionCard>
      </div>

      <div className="grid gap-6 xl:grid-cols-3">
        <SectionCard title="Confidence Bands" subtitle="Model certainty histogram for all stored scans.">
          <ChartBlock data={data?.confidence_bands ?? []} xKey="band" barKey="count" color="#47c0ff" />
        </SectionCard>
        <SectionCard title="Severity Mix" subtitle="Alert severities generated by the rule and correlation engine.">
          <ChartBlock data={data?.severity_distribution ?? []} xKey="severity" barKey="count" color="#ff6b6b" />
        </SectionCard>
        <SectionCard title="Scan Sources" subtitle="How much of the activity comes from manual uploads versus autonomous watchers.">
          <ChartBlock data={data?.source_breakdown ?? []} xKey="source" barKey="count" color="#57e389" />
        </SectionCard>
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="YARA Hits" subtitle="Most frequent rules that contributed evidence across recent scans.">
          <ChartBlock data={data?.yara_hits ?? []} xKey="rule" barKey="count" color="#ffb84d" />
        </SectionCard>
        <SectionCard title="Watch Folder Activity" subtitle="Which monitored paths are generating the most live events.">
          <ChartBlock data={data?.watch_activity ?? []} xKey="watch_path" barKey="count" color="#22e1c3" />
        </SectionCard>
      </div>
    </main>
  );
}

function ChartBlock({ data, xKey, barKey, color }) {
  return (
    <div className="h-72">
      <ResponsiveContainer>
        <BarChart data={data}>
          <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
          <XAxis dataKey={xKey} tick={{ fill: "#d6e2ef", fontSize: 11 }} interval={0} angle={data.length > 5 ? -20 : 0} textAnchor="end" height={60} />
          <YAxis tick={{ fill: "#d6e2ef", fontSize: 12 }} />
          <Tooltip />
          <Bar dataKey={barKey} fill={color} radius={[8, 8, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}

function CellShim({ fill }) {
  return <Cell fill={fill} />;
}
